print("Renna Mae G. Regio")
print("Matalaba Santa Cruz Marinduque")
print("December 26, 2002")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("2nd year")
print("Section C")